# basic options
title:  Your awesome title
author:  GitHub User
email:  kamal.rkara@gmail.com
description:  A wonderful site
github_username:  KamalanathanN

# Build settings
markdown:  kramdown
theme:  minima
